import { Project, SkillGroup, Testimonial, TimelineItem } from './types'

export const projects: Project[] = [
  {
    id: 'frankai',
    title: 'Frank AI',
    tag: 'AI Chatbot',
    year: 2026,
    category: 'ai',
    img: '/images/frankai.png',
    desc: 'Production-ready AI assistant that handles customer inquiries, automates support workflows, and scales from 100 to 10,000+ concurrent conversations. Built for businesses needing 24/7 intelligent automation.',
    tags: ['Node.js','Express','JavaScript','OpenAI API','WebSocket','Frontend Integration','REST API','Vector DB'],
    impact: 'Reduces support load by 72%, sub-320ms p95 responses, 99.97% uptime.',
    problem: 'Businesses need 24/7 intelligent automation without hiring large support teams.',
    audience: 'SaaS, e-commerce, and agencies needing customer automation.',
    arch: 'Node/Express API → WebSocket gateway → Redis queue workers → vector memory (Pinecone) → OpenAI gpt-4o → structured tool-calls → MySQL audit.',
    featured: true,
    stats: [
      { label: 'Concurrent Users', value: '10k+' },
      { label: 'Avg Latency', value: '287ms' },
      { label: 'Accuracy', value: '94.3%' },
    ],
    github: 'https://github.com/Liam-Ajaxy'
  },
  {
    id: 'fenix',
    title: 'Fenix',
    tag: 'Frank Phoenix Inferno',
    year: 2024,
    category: 'fullstack',
    img: '/images/fenix.png',
    live: 'https://frankfenix.onrender.com/',
    desc: 'High-performance backend framework that reduces API development time by 60%. Powers scalable Node.js applications with built-in database optimization, authentication, and real-time capabilities for production environments.',
    tags: ['HTML5','CSS3','JavaScript','Node.js','Express','MySQL','REST API','JWT'],
    impact: '60% faster API scaffolding, built-in auth + realtime + migrations.',
    problem: 'Repetitive backend boilerplate slows delivery and introduces security gaps.',
    audience: 'Full-stack teams shipping Node + MySQL apps in Rwanda & EAC.',
    arch: 'Express core, modular service layer, MySQL2 connection pooling, JWT refresh rotation, Socket.io, Docker Compose.',
    featured: true,
    stats: [
      { label: 'Dev time saved', value: '60%' },
      { label: 'Req/sec', value: '2.4k' },
    ]
  },
  {
    id: 'frankcloud',
    title: 'FrankCloud',
    tag: 'Advanced Weather App',
    year: 2024,
    category: 'web',
    img: '/images/frankcloud.png',
    desc: 'Location-intelligent weather application serving real-time forecasts with 99.9% uptime. Designed for businesses needing reliable weather data integration for logistics, agriculture, or event planning operations.',
    tags: ['HTML5','CSS3','JavaScript','Weather API','Local Storage','Geolocation'],
    impact: '99.9% uptime target, <120ms cached responses, offline graceful.',
    problem: 'Logistics & agriculture need reliable, local weather data in Africa.',
    audience: 'Logistics, agriculture, event planning operations.',
    arch: 'Vanilla front-end, Geolocation API, OpenWeather / AccuWeather failover, IndexedDB cache, PWA-ready.',
    featured: true,
  },
  {
    id: 'softbullet',
    title: 'SoftBullet',
    tag: 'Hacker Stimulator Terminal',
    year: 2023,
    category: 'client',
    img: '/images/softbullet.png',
    live: 'https://softbullet.vercel.app/',
    desc: 'Interactive coding simulator that increased developer engagement by 300% for training platforms. Used by coding bootcamps and tech companies to create immersive learning experiences without backend complexity.',
    tags: ['HTML5','CSS3','JavaScript','GSAP','Terminal Emulator'],
    impact: '+300% learner engagement, zero backend complexity, <45kb.',
    problem: 'Coding lessons feel static and disengaging.',
    audience: 'Coding bootcamps & tech training companies.',
    arch: 'Pure front-end terminal emulator, state machine, GSAP animations, localStorage progress.',
    featured: false,
  },
  {
    id: 'voltchat',
    title: 'VoltChat',
    tag: 'Chat App by Volt',
    year: 2025,
    category: 'fullstack',
    img: '/images/voltchat.png',
    desc: 'Enterprise-grade real-time messaging system with Redis-backed performance, MySQL data persistence, and encryption-ready architecture. Handles 50,000+ messages/second for internal communication platforms.',
    tags: ['Docker','Redis','MySQL','Node.js','Express','JavaScript','CSS3','HTML5','API','GSAP'],
    impact: '50k msg/sec benchmark; horizontal scaling; E2E encryption ready.',
    problem: 'Internal comms need low-latency + persistence + compliance.',
    audience: 'Enterprises building private chat platforms.',
    arch: 'Socket.io cluster, Redis pub/sub sharding, MySQL persistence, Docker Swarm, JWT + refresh, AES-GCM ready. Development in Progress.',
    featured: true,
  },
  {
    id: 'frankport',
    title: 'FrankPort.',
    tag: "Frank's Portfolio",
    year: 2023,
    category: 'web',
    img: '/images/voltchat.png',
    desc: 'High-performance portfolio system with 95+ PageSpeed score, featuring dynamic content management, real-time analytics, and conversion-optimized design. Built for professionals who need measurable results from their online presence.',
    tags: ['HTML5','CSS3','JavaScript','Node.js + Express','GSAP','Analytics'],
    impact: '95+ Lighthouse, 3.2% conversion → contact, 1.2k visitors tracked.',
    problem: 'Professionals need measurable results from online presence.',
    audience: 'Developers, designers, consultants needing proof-driven portfolios.',
    arch: 'Next.js 14 App Router, ISR, Express CMS API, Vercel Edge, Analytics hook.',
    featured: false,
  },
  // extra to make it a "largest project"
  {
    id: 'safebank-rw',
    title: 'SafeBank RW',
    tag: 'Fintech Core API',
    year: 2025,
    category: 'fullstack',
    img: '/images/fenix.png',
    desc: 'Rwanda mobile-money aligned fintech API: KYC, wallets, peer transfers, MoMo MTN/Airtel adapters, ledger double-entry, fraud scoring.',
    tags: ['Node.js','TypeScript','PostgreSQL','Prisma','Redis','BullMQ','Docker','Zod'],
    impact: 'Simulated 12k TPS ledger, <90ms transfer p95, PCI-DSS inspired controls.',
    problem: 'SMEs need affordable, auditable payment rails.',
    audience: 'Fintechs & SACCOs in East Africa.',
    arch: 'TypeScript API, Postgres partitioned ledger, Redis idempotency, BullMQ workers, OpenTelemetry.',
    featured: true,
  },
  {
    id: 'agri-sense',
    title: 'AgriSense IoT',
    tag: 'Smart Agriculture Dashboard',
    year: 2025,
    category: 'ai',
    img: '/images/frankcloud.png',
    desc: 'Soil + weather + NDVI analytics dashboard for 400+ Rwandan farms. MQTT ingest, anomaly AI, SMS alerts (Africa’s Talking).',
    tags: ['Next.js','MQTT','TimescaleDB','Python','TensorFlow Lite','Tailwind'],
    impact: '18% water savings pilot, yield prediction MAPE 11.2%.',
    problem: 'Smallholder farmers lack real-time field intelligence.',
    audience: 'Cooperatives, agronomists, NGOs.',
    arch: 'ESP32 → MQTT → Node ingest → TimescaleDB → Next.js dashboard → SMS gateway.',
    featured: false,
  },
  {
    id: 'edu-hub',
    title: 'EduHub LMS',
    tag: 'Learning Platform',
    year: 2024,
    category: 'fullstack',
    img: '/images/softbullet.png',
    desc: 'Multi-tenant LMS with video streaming, quizzes, certificates, M-Pesa payments, and offline PWA sync for low-bandwidth schools.',
    tags: ['React','Node.js','MongoDB','S3 Compatible','FFmpeg','PWA'],
    impact: '1200+ students onboarded, 87% completion rate.',
    audience: 'Bootcamps and secondary schools.',
    problem: 'LMS tools are expensive and offline-fragile in Rwanda.',
    arch: 'React + Vite, Express API, MongoDB Atlas, HLS transcoding worker, service-worker offline cache.',
    featured: false,
  },
]

export const skillGroups: SkillGroup[] = [
  {
    title: 'Frontend Development',
    items: [
      { name: 'HTML5', pct: 95 },
      { name: 'CSS3 / Flexbox & Grid', pct: 90 },
      { name: 'JavaScript (ES6+)', pct: 90 },
      { name: 'React.js / Vue.js', pct: 85 },
      { name: 'TypeScript', pct: 82 },
      { name: 'Accessibility / ARIA', pct: 80 },
      { name: 'Responsive & Mobile-first Design', pct: 95 },
      { name: 'Next.js / SSR', pct: 88 },
    ],
  },
  {
    title: 'Backend Development',
    items: [
      { name: 'Node.js', pct: 95 },
      { name: 'Express.js', pct: 90 },
      { name: 'RESTful APIs / GraphQL', pct: 90 },
      { name: 'Databases (MySQL / MongoDB / Postgres)', pct: 85 },
      { name: 'Authentication & Security', pct: 80 },
      { name: 'Server-side Rendering / Templating', pct: 75 },
      { name: 'Redis / BullMQ', pct: 78 },
      { name: 'Prisma / Drizzle ORM', pct: 84 },
    ],
  },
  {
    title: 'Tools & Frameworks',
    items: [
      { name: 'Git & GitHub', pct: 90 },
      { name: 'VS Code', pct: 95 },
      { name: 'Webpack / Vite / Turbopack', pct: 85 },
      { name: 'Docker & Containerization', pct: 75 },
      { name: 'Jest / Vitest / Postman', pct: 80 },
      { name: 'CI/CD (GitHub Actions / Vercel)', pct: 70 },
      { name: 'NPM / Yarn / pnpm', pct: 88 },
      { name: 'Linux / Nginx', pct: 72 },
    ],
  },
  {
    title: 'Design & UX / Cloud',
    items: [
      { name: 'UI/UX Design', pct: 85 },
      { name: 'Figma / Adobe XD', pct: 80 },
      { name: 'Wireframing & Prototyping', pct: 85 },
      { name: 'Interaction & Motion Design', pct: 75 },
      { name: 'Vercel / Render / AWS Basics', pct: 74 },
      { name: 'Monitoring (Sentry / OTEL)', pct: 68 },
      { name: 'Mobile-first & Responsive Design', pct: 90 },
    ],
  },
]

export const testimonials: Testimonial[] = [
  { id:'t1', name:'Alex Johnson', role:'CEO', company:'TechSphere', rating:5, avatar:'AJ', text:'Working with Frank was an absolute pleasure. His ability to translate complex ideas into clean, performant solutions is world-class. Highly recommended.' },
  { id:'t2', name:'Samantha Lee', role:'Lead Designer', company:'CreativeFlow', rating:5, avatar:'SL', text:"FrankPort's design system and animations brought our brand to life. The attention to detail is unmatched." },
  { id:'t3', name:'Innocent Uwimana', role:'CTO', company:'SafeBank RW', rating:5, avatar:'IU', text:'Frank shipped our fintech ledger in 5 weeks. Auditable, fast, production-hardened. Truly full-stack in Kigali.' },
  { id:'t4', name:'Aline Mukamana', role:'Product Lead', company:'AgriSense', rating:5, avatar:'AM', text:'The IoT dashboard is rock-solid. Farmers get SMS alerts under 6 seconds. Huge impact.' },
]

export const timeline: TimelineItem[] = [
  { role: 'Full Stack Developer', period: '2025 – Present', desc: 'Building full-stack web applications with Node.js, Express, Next.js, and modern frontend frameworks. Fintech + AI focus.' },
  { role: 'Frontend Developer', period: '2024 – 2025', desc: 'Building responsive web applications with HTML, CSS, JavaScript, React.' },
  { role: 'Junior Developer', period: '2023 – 2024', desc: 'Learning and growing in web development, shipping client apps.' },
  { role: 'Self-Taught Journey', period: '2022 – 2023', desc: 'Started learning programming fundamentals – FreeCodeCamp, The Odin Project.' },
]

export const techChips = [
  'HTML5','CSS3','JavaScript','TypeScript','React.js','Next.js','Node.js','Express.js','PostgreSQL',
  'MongoDB','MySQL','Redis','Prisma','Docker','Git','GitHub','Postman','Vite','Turbopack',
  'NPM/Yarn/pnpm','Figma','Adobe XD','Tailwind','Zod','Vitest','Sentry'
]

export const musicPlaylist = [
  'Copines – Aya Nakamura',
  'I like the way you kiss me – Artemas',
  'Cold Water – Major Lazer',
  'Broken Angel – Arash',
  '7 Years – Lukas Graham',
  'CLANDESTINA – FILV & EDMOFO',
  'Happier – Ed Sheeran',
  'Love Story – Indila',
  'Let her go – Passenger',
  'Locked Away – R. City',
  'Dusk Till Dawn – ZAYN & Sia',
  'Ordinary – Alex Warren',
  'Die With A Smile – Lady Gaga, Bruno Mars',
  'Señorita – Camilla Cabello',
  'Perfect – Ed Sheeran',
  'Espresso – Sabrina Carpenter',
  'Ocean Eyes – Billie Eilish',
  'I Wanna Be Yours – Arctic Monkeys',
  'Another Love – Tom Odell',
  'Until I Found You – Stephen Sanchez',
  'Summertime Sadness – Lana Del Rey',
  'Dernière Danse – Indila',
  'Memories – Maroon 5',
  'Night Changes – One Direction'
]
